usr1 = 1
usr2 = 2

ds_dev = 1
ds_test = 2

an_type_data = 1
an_type_dev = 2
an_type_test = 3
an_type_model = 4

lbl_9k = "concepts_9k"
lbl_oi = "concepts_oi"

top_id = "id"
top_idi = "id_int"
top_type = "type"
top_usr = "uid"
top_title = "title"
top_desc = "description"
top_narrative = "narrative"

vc_cat_cols = [
    "category_top01",
    "category_top02",
    "category_top03",
    "category_top04",
    "category_top05",
]

vc_cat_score_cols = [
    "category_top01_score",
    "category_top02_score",
    "category_top03_score",
    "category_top04_score",
    "category_top05_score",
]

vc_att_cols = [
    "attribute_top01",
    "attribute_top02",
    "attribute_top03",
    "attribute_top04",
    "attribute_top05",
    "attribute_top06",
    "attribute_top07",
    "attribute_top08",
    "attribute_top09",
    "attribute_top10",
]

vc_con_cols = [
    "concept_class_top01",
    "concept_class_top02",
    "concept_class_top03",
    "concept_class_top04",
    "concept_class_top05",
    "concept_class_top06",
    "concept_class_top07",
    "concept_class_top08",
    "concept_class_top09",
    "concept_class_top10",
    "concept_class_top11",
    "concept_class_top12",
    "concept_class_top13",
    "concept_class_top14",
    "concept_class_top15",
    "concept_class_top16",
    "concept_class_top17",
    "concept_class_top18",
    "concept_class_top19",
    "concept_class_top20",
    "concept_class_top21",
    "concept_class_top22",
    "concept_class_top23",
    "concept_class_top24",
    "concept_class_top25",
]

vc_cols = [
    "image_id",
    "image_path",
    "attribute_top01",
    "attribute_top02",
    "attribute_top03",
    "attribute_top04",
    "attribute_top05",
    "attribute_top06",
    "attribute_top07",
    "attribute_top08",
    "attribute_top09",
    "attribute_top10",
    "category_top01",
    "category_top01_score",
    "category_top02",
    "category_top02_score",
    "category_top03",
    "category_top03_score",
    "category_top04",
    "category_top04_score",
    "category_top05",
    "category_top05_score",
    "concept_class_top01",
    "concept_score_top01",
    "concept_bbox_top01",
    "concept_class_top02",
    "concept_score_top02",
    "concept_bbox_top02",
    "concept_class_top03",
    "concept_score_top03",
    "concept_bbox_top03",
    "concept_class_top04",
    "concept_score_top04",
    "concept_bbox_top04",
    "concept_class_top05",
    "concept_score_top05",
    "concept_bbox_top05",
    "concept_class_top06",
    "concept_score_top06",
    "concept_bbox_top06",
    "concept_class_top07",
    "concept_score_top07",
    "concept_bbox_top07",
    "concept_class_top08",
    "concept_score_top08",
    "concept_bbox_top08",
    "concept_class_top09",
    "concept_score_top09",
    "concept_bbox_top09",
    "concept_class_top10",
    "concept_score_top10",
    "concept_bbox_top10",
    "concept_class_top11",
    "concept_score_top11",
    "concept_bbox_top11",
    "concept_class_top12",
    "concept_score_top12",
    "concept_bbox_top12",
    "concept_class_top13",
    "concept_score_top13",
    "concept_bbox_top13",
    "concept_class_top14",
    "concept_score_top14",
    "concept_bbox_top14",
    "concept_class_top15",
    "concept_score_top15",
    "concept_bbox_top15",
    "concept_class_top16",
    "concept_score_top16",
    "concept_bbox_top16",
    "concept_class_top17",
    "concept_score_top17",
    "concept_bbox_top17",
    "concept_class_top18",
    "concept_score_top18",
    "concept_bbox_top18",
    "concept_class_top19",
    "concept_score_top19",
    "concept_bbox_top19",
    "concept_class_top20",
    "concept_score_top20",
    "concept_bbox_top20",
    "concept_class_top21",
    "concept_score_top21",
    "concept_bbox_top21",
    "concept_class_top22",
    "concept_score_top22",
    "concept_bbox_top22",
    "concept_class_top23",
    "concept_score_top23",
    "concept_bbox_top23",
    "concept_class_top24",
    "concept_score_top24",
    "concept_bbox_top24",
    "concept_class_top25",
    "concept_score_top25",
    "concept_bbox_top25",
]

vc_cols_c = len(vc_cols)

mbt_cols = [
    "minute_ID",
    "utc_time",
    "local_time",
    "time_zone",
    "lat",
    "lon",
    "name",
    "song",
    "activity",
    "steps",
    "calories",
    "historic_glucose (mmol/L)",
    " scan_glucose (mmol/L)",
    "heart_rate",
    "distance",
    "img00_id",
    "img01_id",
    "img02_id",
    "img03_id",
    "img04_id",
    "img05_id",
    "img06_id",
    "img07_id",
    "img08_id",
    "img09_id",
    "img10_id",
    "img11_id",
    "img12_id",
    "img13_id",
    "img14_id",
    "img15_id",
    "img16_id",
    "img17_id",
    "img18_id",
    "img19_id",
    "cam00_id",
    "cam01_id",
    "cam02_id",
    "cam03_id",
    "cam04_id",
    "cam05_id",
    "cam06_id",
    "cam07_id",
    "cam08_id",
    "cam09_id",
    "cam10_id",
    "cam11_id",
    "cam12_id",
    "cam13_id",
    "cam14_id", 
]

mbt_id_cols = [
    "img00_id",
    "img01_id",
    "img02_id",
    "img03_id",
    "img04_id",
    "img05_id",
    "img06_id",
    "img07_id",
    "img08_id",
    "img09_id",
    "img10_id",
    "img11_id",
    "img12_id",
    "img13_id",
    "img14_id",
    "img15_id",
    "img16_id",
    "img17_id",
    "img18_id",
    "img19_id",
    "cam00_id",
    "cam01_id",
    "cam02_id",
    "cam03_id",
    "cam04_id",
    "cam05_id",
    "cam06_id",
    "cam07_id",
    "cam08_id",
    "cam09_id",
    "cam10_id",
    "cam11_id",
    "cam12_id",
    "cam13_id",
    "cam14_id", 
]

mbt_cols_c = len(mbt_cols)
